version: "3"

services:
    redis-1:
      image: redis:alpine
      ports:
        - "6379:6379"
      networks:
        - ledger

    redis-2:
      image: redis:alpine
      ports:
        - "6380:6379"
      networks:
        - ledger

    redis-3:
      image: redis:alpine
      ports:
        - "6381:6379"
      networks:
        - ledger

    mongodb:
      image: mongo:4-bionic
      restart: always
      ports:
        - "27017:27017"
      networks:
        - ledger

networks:
  ledger:
    driver: bridge
